### ISSUE TITLE
bug or my code is shit

### ISSUE THREAD

**Issue by int3iku** [Baraban4ik/EcoLobby#13]
please help, the "[PLAYER] /captcha" command does not work when logging into the server

![image](https://github.com/user-attachments/assets/7654bc0c-4f64-4f7f-9473-41785bab432e)

**Comment by int3iku** [comment]
please add to "AVAILABLE ACTIONS" so execution time can be set

for example it will be executed in 3 or 5 seconds

**Comment by Baraban4ik** [comment]
You need to use it without a slash!
Вы должны использовать его без слэша!

- "[PLAYER] captcha"

**Comment by int3iku** [comment]
yes I tried without the slash but no luck

and this is what I found out, the commands are executed immediately, without even checking the whitelisted commands, this should not be the case, because the command must be sent on behalf of the player. For example:
  actions:
    - “[PLAYER] captcha”
    - “[PLAYER] help”

the /help command will be executed even if it is not in the list

at least in the well-known menu plugin the logic for sending a command is this

please resolve this issue, because the command is not sent on behalf of the player

and as for the action timer, the request is still valid

**Comment by Baraban4ik** [comment]
I added a timer for actions
In the trail. this bug will be fixed in the update
