### ISSUE TITLE
server security

### ISSUE THREAD

**Issue by int3iku** [Baraban4ik/EcoLobby#14]
please make whitelisting game commands work even with OP or *

**Comment by Baraban4ik** [comment]
This is how they work, if you don't have any, then you need more information
Они так и работают, если у вас нет, то нужно больше информации

**Comment by int3iku** [comment]
oh, sorry, Google translator made a mistake and translated it wrong

I meant that it is necessary to limit the players OP or *, because if someone gets these rights, then he can harm the server, and if his commands are not passed through the whitelist commands, then the attacker will only have to cry

**Comment by Baraban4ik** [comment]
That is, you want that even if you are an op, the commands are not executed
Also, what language is convenient for you to communicate in?

**Comment by int3iku** [comment]
yes, that’s right, you need to make sure that the white list of commands is absolute, that is, so that unwritten commands are accepted only from the console

don't worry about the language, I don't care what it is

and also thank you very much for update 1.3.1

**Comment by Baraban4ik** [comment]
Okay, but then the bypass permission would be useless
I wouldn't want it to become one!
