### ISSUE TITLE
ecolobby.bypass.commands не работает

### ISSUE THREAD

**Issue by int3iku** [Baraban4ik/EcoLobby#18]
я выдал отрицательное разрешение на ecolobby.bypass.commands в luckpermsvelocity, но в лобби игроки с OP всё равно могут использовать команды

**Comment by int3iku** [comment]
![image](https://github.com/user-attachments/assets/8e42da08-4663-4bd9-918f-16af21166035)

**Comment by int3iku** [comment]
и спасибо за опыт общения на английском :D

**Comment by Baraban4ik** [comment]
> я выдал отрицательное разрешение на ecolobby.bypass.commands в luckpermsvelocity, но в лобби игроки с OP всё равно могут использовать команды

Оно так работать не будет, нужно довать через обычный luckperms плагин, находиться не на velocity
Ну или подключать все к одной БД
