### ISSUE TITLE
Spawn teleport, repeated join item and crop trampling.

### ISSUE THREAD

**Issue by PlayMercyMC** [Baraban4ik/EcoLobby#3]
Hello, I love your plugin but i believe i found 3 minor bugs.

- I use the plugin GSit in my server and it allows players to sit on top of each other, if a player is sitting on top of another and jumps down the void, the spawn teleportation built into EcoLobby does not work and they fall forever. 

- The second issue is related to the join item i set up, sometimes for some reason players have 2 instances of the same item in their inventory, they stack up. I have the clear inventory setting turned on and it happens when they relog, only sometimes though. 

- And lastly, even with break blocks disabled, players are able to trample crops, jumping on top of crops will break them, I wish I didn't have to use worldguard because this plugin is very complete but it's up to you if you want to prevent that.
- 
Thank you, and keep up the good work, your plugin is awesome.

**Comment by Baraban4ik** [comment]
Thanks, I'm not sure about GSit, but I'll fix everything else.
