### ISSUE TITLE
No support for HEX Colors in the tab list

### ISSUE THREAD

**Issue by ghost** [Baraban4ik/EcoLobby#5]
Hello, I am using the latest version of the plugin. There is no support for HEX colors in the tabulator. Although the plugin page says that HEX colors are supported. What is the problem?

I am from Russia, I write through a translator, so I apologize for possible mistakes in my message.

**Comment by Baraban4ik** [comment]
Убедись, что вы используете данный формат #hex, например: #ffffff
Если все верно, я бы хотел узнать, какое ядро вы используете

**Comment by ghost** [comment]
Благодарю за оперативную помощь. Проблема решена.
